# Generated by Django 3.1.4 on 2020-12-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(choices=[('r1', 'Good'), ('r2', 'Family'), ('r3', 'Lux')], max_length=100),
        ),
    ]
